// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "serDemo.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class serDemoHandler : virtual public serDemoIf {
 public:
  serDemoHandler() {
    // Your initialization goes here
  }

  void put(const message& msg) {
    // Your implementation goes here
    printf("put\n");
    printf("receive message: id: %d, content: %s\n", msg.seqId, msg.content.c_str()); 
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<serDemoHandler> handler(new serDemoHandler());
  shared_ptr<TProcessor> processor(new serDemoProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

