/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef serDemo_H
#define serDemo_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "server_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class serDemoIf {
 public:
  virtual ~serDemoIf() {}
  virtual void put(const message& msg) = 0;
};

class serDemoIfFactory {
 public:
  typedef serDemoIf Handler;

  virtual ~serDemoIfFactory() {}

  virtual serDemoIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(serDemoIf* /* handler */) = 0;
};

class serDemoIfSingletonFactory : virtual public serDemoIfFactory {
 public:
  serDemoIfSingletonFactory(const boost::shared_ptr<serDemoIf>& iface) : iface_(iface) {}
  virtual ~serDemoIfSingletonFactory() {}

  virtual serDemoIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(serDemoIf* /* handler */) {}

 protected:
  boost::shared_ptr<serDemoIf> iface_;
};

class serDemoNull : virtual public serDemoIf {
 public:
  virtual ~serDemoNull() {}
  void put(const message& /* msg */) {
    return;
  }
};

typedef struct _serDemo_put_args__isset {
  _serDemo_put_args__isset() : msg(false) {}
  bool msg :1;
} _serDemo_put_args__isset;

class serDemo_put_args {
 public:

  serDemo_put_args(const serDemo_put_args&);
  serDemo_put_args& operator=(const serDemo_put_args&);
  serDemo_put_args() {
  }

  virtual ~serDemo_put_args() throw();
  message msg;

  _serDemo_put_args__isset __isset;

  void __set_msg(const message& val);

  bool operator == (const serDemo_put_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const serDemo_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const serDemo_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class serDemo_put_pargs {
 public:


  virtual ~serDemo_put_pargs() throw();
  const message* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class serDemo_put_result {
 public:

  serDemo_put_result(const serDemo_put_result&);
  serDemo_put_result& operator=(const serDemo_put_result&);
  serDemo_put_result() {
  }

  virtual ~serDemo_put_result() throw();

  bool operator == (const serDemo_put_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const serDemo_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const serDemo_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class serDemo_put_presult {
 public:


  virtual ~serDemo_put_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class serDemoClient : virtual public serDemoIf {
 public:
  serDemoClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  serDemoClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const message& msg);
  void send_put(const message& msg);
  void recv_put();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class serDemoProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<serDemoIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (serDemoProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  serDemoProcessor(boost::shared_ptr<serDemoIf> iface) :
    iface_(iface) {
    processMap_["put"] = &serDemoProcessor::process_put;
  }

  virtual ~serDemoProcessor() {}
};

class serDemoProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  serDemoProcessorFactory(const ::boost::shared_ptr< serDemoIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< serDemoIfFactory > handlerFactory_;
};

class serDemoMultiface : virtual public serDemoIf {
 public:
  serDemoMultiface(std::vector<boost::shared_ptr<serDemoIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~serDemoMultiface() {}
 protected:
  std::vector<boost::shared_ptr<serDemoIf> > ifaces_;
  serDemoMultiface() {}
  void add(boost::shared_ptr<serDemoIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void put(const message& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(msg);
    }
    ifaces_[i]->put(msg);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class serDemoConcurrentClient : virtual public serDemoIf {
 public:
  serDemoConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  serDemoConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const message& msg);
  int32_t send_put(const message& msg);
  void recv_put(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
